dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  auto_route: ^4.0.0
  dio: ^4.0.0
  json_annotation: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  auto_route_generator: ^4.0.0
  json_serializable: ^5.0.0
