name: bafia
description: Barabai Financial Assistant
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  image_picker: ^1.1.2
  get: ^4.3.8
  path: ^1.8.0
  http: ^1.2.1
  intl: ^0.19.0
  sqflite: ^2.0.0+4
  sqflite_common_ffi: ^2.0.1+1
  sqflite_common_ffi_web: '>=0.1.0-dev.1'
  provider: ^6.1.2
  syncfusion_flutter_gauges: ^26.1.40
  flutter_local_notifications: ^17.2.1+1
  firebase_messaging: ^15.0.2
  firebase_core: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  rename: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - 'assets/images/'
    - 'assets/icons/'

flutter_icons:
  android: 'launcher_icon'
  ios: false
  image_path: 'assets/icons/logo.png'
  adaptive_icon_background: 'assets/icons/logo.png'
  adaptive_icon_foreground: 'assets/icons/logo.png'