// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzALO8NlFmYQ-1eQoP8j8FbH7LpkiDMPQ',
    appId: '1:487583025296:web:193c17e25d70948539b015',
    messagingSenderId: '487583025296',
    projectId: 'bafia-428505',
    authDomain: 'bafia-428505.firebaseapp.com',
    storageBucket: 'bafia-428505.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF780b22C2yjZdmGT-XQCXkofW8bo-tNo',
    appId: '1:487583025296:android:dca831457fca37a739b015',
    messagingSenderId: '487583025296',
    projectId: 'bafia-428505',
    storageBucket: 'bafia-428505.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRkVz6T6dUTEvgW4lFnjQvAjuSuSLFzyc',
    appId: '1:487583025296:ios:a90ea3406a46521539b015',
    messagingSenderId: '487583025296',
    projectId: 'bafia-428505',
    storageBucket: 'bafia-428505.appspot.com',
    iosBundleId: 'com.urangbanua.bafia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs9H1N6OUxXDYvnkRqCPWinluIBQyU_wQ',
    appId: '1:648049824628:ios:83f322b3a86b4ce6109221',
    messagingSenderId: '648049824628',
    projectId: 'bpkad-official',
    storageBucket: 'bpkad-official.appspot.com',
    iosBundleId: 'com.urangbanua.bafia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzALO8NlFmYQ-1eQoP8j8FbH7LpkiDMPQ',
    appId: '1:487583025296:web:059b43badbf5598639b015',
    messagingSenderId: '487583025296',
    projectId: 'bafia-428505',
    authDomain: 'bafia-428505.firebaseapp.com',
    storageBucket: 'bafia-428505.appspot.com',
  );

}